### ISSUE TITLE
Package.json fixes

### ISSUE THREAD

**Issue by NathanaelA** [rhanb/nativescript-dev-assets#1]
Hey @rhanb - Hey congrats on your plugin!    I noticed your package.json file is incomplete.   It is not linking back to your github nor is does it have you as the author.  If you need some help with how to lay it out; please see https://plugins.nativescript.rocks/create and it has each of the package.json keys.    And again congrats on getting this cool plugin out!

**Comment by rhanb** [comment]
Hey @NathanaelA , thanks for your help, I completely forgot to complete the package.json! Will correct that 😄
