### ISSUE TITLE
No assets folder found in Android platform

### ISSUE THREAD

**Issue by mudlabs** [rhanb/nativescript-dev-assets#2]
## Can't build app after install

1. `tns install nativescript-dev-assets`
2. Confirmed the addition of an **assets** folder in `app/assets`
3. `tns platform update android`
4. `tns device android` confirmed device was connected
5. `tns run android` errored out with;
```console
Executing before-prepare hook from /hooks/before-prepare/nativescript-dev-assets.js
No assets folder found in Android platform at: /platforms/android/src/main/assets
Unable to apply changes on device: HT247W122555. Error is: Failed to execute hook: /hooks/before-prepare/nativescript-dev-assets.js..
```

**Comment by mudlabs** [comment]
## Solution
Problem was `pathToAndroidPlatformAssets` is checking `platforms/android/src/main/assets` but correct path is `platforms/android/app/src/main/assets`

Is this just a _me_ thing, or should I submit a PR with the changed path?

---
Also when using this plugin you can just specify the _file name_ as `src`. Which is nice. But it only works on Android. 

I know you built it to address an Android issue. But since NativeScript projects are meant for dual platform development, would it make sense to extend this feature to iOS too?

**Comment by rhanb** [comment]
Hi @mudlabs ,

`pathToAndroidPlatformAssets` has the path `platforms/android/src/main/assets` which is normal, since it's the place where you put assets in `Android` not in `platforms/android/app/src/main/assets`. Which means that your issue comes from something else, from your output, I see that you don't have the `platforms/android/src/main/assets` which is normally automatically created by {N}. Try to delete your `platforms` folder, run again `tns prepare android` and check if the `platforms/android/src/main/assets`exists`.

If not please provide me your dependencies in your `package.json` please 

 ---
And for iOS, you're right it would be better to have aller your assets in the same place, I'll dig into that :)

**Comment by mudlabs** [comment]
**Did not work**

1. Deleted `platforms`
2. `tns prepare android`
3. `cd platforms/android/src/main/assets` => No such file or directory

**Dependencies**
```json
"dependencies": {
    "nativescript-dom": "^2.0.0",
    "nativescript-lottie": "^1.3.1",
    "nativescript-sound": "^1.0.4",
    "nativescript-theme-core": "1.0.4",
    "tns-core-modules": "^3.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "eslint": "4.9.0",
    "lazy": "1.0.11",
    "nativescript-dev-assets": "0.0.3",
    "nativescript-dev-sass": "1.3.0"
  }
```

**Comment by rhanb** [comment]
@mudlabs thanks for your feedback. 

I see that you use the latest {N} version, I test it under the 3.3. Let me upgrade and test that out, it's possible that the hooks changed between the two versions.

PS: iOS part almost done

**Comment by evanfuture** [comment]
"nativescript-hook": "^0.2.1"

**Comment by rhanb** [comment]
@mudlabs effectively the issue comes from the changes made to the `platforms` folder in the latest {N} version. fix coming soon

**Comment by rhanb** [comment]
@mudlabs , I've got an issue with the iOS support. I manage to sync the files at the right place in the `platforms/ios` folder, but a config file is edited during the build process which list the ressources files and unfortunately even though the files are synced at the right place, the files aren't listed in the config file which means that you won't be able to use those resources. iOS won't be supported for now

**Comment by mudlabs** [comment]
Oh well. It would be the optimal solution, but it's not that hard to use `ios:src` and `android:src`.
